name: Create Release
on:
  push:
    tags:
      - '*'

env:
  GH_TOKEN: ${{github.token}}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag
        uses: olegtarasov/get-tag@v2.1.2
        id: tag
      - run: gh release create $GIT_TAG_NAME --generate-notes
