name: Create Release
on:
  push:
    tags:
      - '*'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag
        uses: dawidd6/action-get-tag@v1
        id: tag
      - run: gh release create ${{steps.tag.outputs.tag}} --generate-notes
